## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - INFRA-SETUP
  - CLUSTER-CONNECT
  - OPENEBS-INSTALL
  - CLUSTER-CLEANUP

## Setup kubernetes cluster using Rancher
cluster-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/setup
    - ./stages/cluster-setup/setup

## Deploy Director On-Prem
TCID-DIR-INSTALL-ON-LOCAL-HP:
  image: harshshekhar15/gitlab-job:v2
  stage: INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP
    - ./stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP

create-api-key:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/create-apikey
    - ./stages/cluster-connect/create-apikey

cluster-connect:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/cluster-connect
    - ./stages/cluster-connect/cluster-connect

client-components-check:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/client-components-check
    - ./stages/cluster-connect/client-components-check

tcid-iuoi02-openebs-install:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-INSTALL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/tcid-iuoi02-openebs-install
    - ./stages/openebs-install/tcid-iuoi02-openebs-install

TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-INSTALL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE
    - ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE

e2e-metrics:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CLEANUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-cleanup/e2e-metrics
    - ./stages/cluster-cleanup/e2e-metrics

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/cluster-cleanup/cleanup
    - ./stages/cluster-cleanup/cleanup

cluster2-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/cluster-cleanup/cluster2-cleanup
    - ./stages/cluster-cleanup/cluster2-cleanup