## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - INFRA-SETUP
  - CLUSTER-CONNECT
  - DIRECTOR-GUI
  - OPENEBS-SETUP
  - OPENEBS-FUNCTIONAL
  - OPENEBS-CHAOS
  - CLUSTER-CLEANUP

## Setup kubernetes cluster using Rancher
cluster-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/setup
    - ./stages/cluster-setup/setup

cluster2-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster2-setup
    - ./stages/cluster-setup/cluster2-setup

cluster3-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster3-setup
    - ./stages/cluster-setup/cluster3-setup

## Deploy Director On-Prem
TCID-DIR-INSTALL-ON-LOCAL-HP:
  image: harshshekhar15/gitlab-job:v2
  stage: INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP
    - ./stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP

## Selenium Grid Spin up
selenium-grid-deploy:
  image: harshshekhar15/gitlab-job:v5
  stage: INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/infra-setup/selenium-grid-deploy
    - ./stages/infra-setup/selenium-grid-deploy

create-api-key:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/create-apikey
    - ./stages/cluster-connect/create-apikey

cluster-connect:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/cluster-connect
    - ./stages/cluster-connect/cluster-connect

client-components-check:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/client-components-check
    - ./stages/cluster-connect/client-components-check

cluster3-connect:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/cluster3-connect
    - ./stages/cluster-connect/cluster3-connect

client3-components-check:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/client3-components-check
    - ./stages/cluster-connect/client3-components-check

TCID-DIR-OP-INSTALL-OPENEBS:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS
    - ./stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS

TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE
    - ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE

OPENEBS-STORAGE-POLICIES:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/openebs-storage-policies
    - ./stages/openebs-install/openebs-storage-policies

## GUI Checks
TCID-GUI-AUTH:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/gui-auth
    - ./stages/director-gui/gui-auth

TCID-GUI-CLUSTER:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/gui-cluster
    - ./stages/director-gui/gui-cluster

TCID-GUI-DASHBOARD:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/gui-dashboard
    - ./stages/director-gui/gui-dashboard

TCID-GUI-PROFILE:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/gui-profile
    - ./stages/director-gui/gui-profile

## Functional Tests
Jiva-App-Target-Affinity:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/Jiva-App-Target-Affinity/app-target-affinity
    - ./stages/functional/Jiva-App-Target-Affinity/app-target-affinity

Jiva-Snapshot:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/Jiva-snapshot/jiva-snapshot
    - ./stages/functional/Jiva-snapshot/jiva-snapshot

Jiva-Volume-Scaleup:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/Jiva-Volume-Scaleup/jiva-vol-scaleup
    - ./stages/functional/Jiva-Volume-Scaleup/jiva-vol-scaleup

cStor-csi-volume-snapshot:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/cstor-csi-volume-snapshot/csi-cstor-snapshot
    - ./stages/functional/cstor-csi-volume-snapshot/csi-cstor-snapshot

cStor-csi-volume-clone:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/cstor-csi-volume-clone/csi-cstor-clone
    - ./stages/functional/cstor-csi-volume-clone/csi-cstor-clone

cStor-ext4-volume-resize:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/cstor-ext4-volume-resize/csi-volume-resize
    - ./stages/functional/cstor-ext4-volume-resize/csi-volume-resize

cStor-xfs-volume-resize:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/cstor-xfs-volume-resize/csi-volume-resize-xfs
    - ./stages/functional/cstor-xfs-volume-resize/csi-volume-resize-xfs

LocalPV-device:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/local-pv-device/local-pv-device
    - ./stages/functional/local-pv-device/local-pv-device

LocalPV-hostpath:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional/local-pv-hostpath/local-pv-hostpath
    - ./stages/functional/local-pv-hostpath/local-pv-hostpath

# CHAOS Tests JOB

Jiva-App-Kill:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/chaos/Jiva-App-kill/jiva-app-kill
    - ./stages/chaos/Jiva-App-kill/jiva-app-kill

Jiva-Revision-Counter:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/chaos/Jiva-revision-counter/jiva-revision-counter
    - ./stages/chaos/Jiva-revision-counter/jiva-revision-counter

Jiva-Replica-Network-Delay:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/chaos/Jiva-Replica-Network-Delay/jiva-replica-network-delay
    - ./stages/chaos/Jiva-Replica-Network-Delay/jiva-replica-network-delay

Jiva-Controller-Kill:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/chaos/Jiva-Controller-kill/jiva-controller-kill
    - ./stages/chaos/Jiva-Controller-kill/jiva-controller-kill

Jiva-Controller-Network-Delay:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/chaos/Jiva-Controller-Network-Delay/ctrl-network-delay
    - ./stages/chaos/Jiva-Controller-Network-Delay/ctrl-network-delay

Jiva-Replica-Node-Affinity:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/chaos/Jiva-Replica-Node-Affinity/rep-node-affinity
    - ./stages/chaos/Jiva-Replica-Node-Affinity/rep-node-affinity

cStor-App-kill:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/chaos/cstor-App-pod-kill/app-kill
    - ./stages/chaos/cstor-App-pod-kill/app-kill

cStor-Target-kill:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/chaos/cstor-Target-kill/target-kill
    - ./stages/chaos/cstor-Target-kill/target-kill

## Selenium Grid Clean up
selenium-grid-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v5
  stage: CLUSTER-CLEANUP
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/cluster-cleanup/selenium-grid-cleanup
    - ./stages/cluster-cleanup/selenium-grid-cleanup

e2e-metrics:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CLEANUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-cleanup/e2e-metrics
    - ./stages/cluster-cleanup/e2e-metrics

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/cluster-cleanup/cleanup
    - ./stages/cluster-cleanup/cleanup

cluster2-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/cluster-cleanup/cluster2-cleanup
    - ./stages/cluster-cleanup/cluster2-cleanup

cluster3-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/cluster-cleanup/cluster3-cleanup
    - ./stages/cluster-cleanup/cluster3-cleanup
